JUDGE0_TELEMETRY_ENABLE=false
ENABLE_WAIT_RESULT=true
USE_DOCS_AS_HOMEPAGE=true

AUTHN_HEADER=
AUTHN_TOKEN=

REDIS_HOST=judge0-redis
REDIS_PASSWORD=judge0_redis_password_change_me

POSTGRES_HOST=judge0-db
POSTGRES_DB=judge0
POSTGRES_USER=judge0
POSTGRES_PASSWORD=judge0_postgres_password_change_me

RAILS_ENV=production
