// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//import "dotenv/config";
//import { defineConfig } from "prisma/config";
//
//export default defineConfig({
//  schema: "prisma/schema.prisma",
//  migrations: {
//    path: "prisma/migrations",
//  },
//  datasource: {
//    // ✨ Prisma 7 requires this here! It safely evaluates the Docker runtime URL.
//    url: process.env.DATABASE_URL || "postgresql://studyadmin:studypass123@localhost:5432/studyroom_db?schema=public",
//  },
//  //datasource: {
//  //  url: process.env["DATABASE_URL"],
//  //},
//});
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  // Force Prisma to find the schema file correctly
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Read the injected Docker compose URL, otherwise use local fallback
    url: process.env.DATABASE_URL || "postgresql://studyadmin:studypass123@127.0.0.1:5432/studyroom_db?schema=public",
  },
});