// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//import "dotenv/config";
//import { defineConfig } from "prisma/config";
//
//export default defineConfig({
//  schema: "prisma/schema.prisma",
//  migrations: {
//    path: "prisma/migrations",
//  },
//  datasource: {
//    // ✨ Prisma 7 requires this here! It safely evaluates the Docker runtime URL.
//    url: process.env.DATABASE_URL || "postgresql://studyadmin:studypass123@localhost:5432/studyroom_db?schema=public",
//  },
//  //datasource: {
//  //  url: process.env["DATABASE_URL"],
//  //},
//});
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url:
      process.env.DATABASE_URL ||
      "postgresql://postgres:prar0210thna@localhost:5432/studyplatform?schema=public",
  },
});